# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
